### ISSUE TITLE
Out-of-the box support for auto formatting controlled via .dir-locals.el

### ISSUE THREAD

**Issue by pennersr** [lassik/emacs-format-all-the-code#105]
I am working on many projects simultaneously, some of which use automatic code formatting, others do not. Therefore, I would like to enable automatic formatting on a per project basis. 

Proposal:

- Introduce a new variable: `auto-format-all-modes`, which lists all modes for which auto formatting should be turned on.
- Introduce a new mode: `auto-format-all-mode`. When this mode is enabled, and, the major mode you're working in is listed in `auto-format-all-modes`, then `format-all-buffer--from-hook` will automatically run before saving.

Given the above, you can then turn on `auto-format-all-mode` globally, and put the following in you `.dir-locals.el` for a project for which Python files should be automatically formatted:

```
((nil . ((auto-format-all-modes . (python-mode)))))
```

Ofcourse, I can easily add this to my own Emacs init files, but then I would not be able to share the `.dir-locals.el` with colleagues as they would need to replicate the exact same setup. Therefore, it would be good to add support for this out of the box.

**Comment by lassik** [comment]
The `.dir-locals.el` feature you seek can be done more generally by talking about languages instead of modes. (format-all currently uses (GitHub Linguist](https://github.com/github/linguist) language names.)

Anyway, the things you ask for should now work: https://github.com/lassik/emacs-format-all-the-code/issues/27#issuecomment-731600683 Let me know in that thread if anything doesn't work or is unclear!
