### ISSUE TITLE
auto format config doesn't work anymore

### ISSUE THREAD

**Issue by c02y** [lassik/emacs-format-all-the-code#108]
I have been using the following code snippet copied from https://github.com/lassik/emacs-format-all-the-code/blob/master/format-all.el#L1027-L1041 for a while now.

It used to be working for source code such as C/C++, Rust, fish-shell scripts, but recently I updated my spacemacs repo and all the packages, and noticed that the auto-format feature doesn't work anymore

Here is my own config of format-all
~~~
(defvar my-auto-format-modes '(c-mode c++-mode cmake-mode emacs-lisp-mode
                                        fish-mode go-mode json-mode lua-mode
                                        markdown-mode python-mode rust-mode
                                        sh-mode toml-mode yaml-mode))
  (defvar my-auto-format-dirs '("" ""))
  (defun my-auto-format-buffer-p ()
    (and (member major-mode my-auto-format-modes)
         (buffer-file-name)
         (save-match-data
           (let ((dir (file-name-directory (buffer-file-name))))
             (cl-some (lambda (regexp) (string-match regexp dir))
                      my-auto-format-dirs)))))
  (defun format-buffer-before-save ()
    (format-all-mode (if (my-auto-format-buffer-p) 1 0)))
  (add-hook 'after-change-major-mode-hook 'format-buffer-before-save)
~~~

I tried it using `emacs -q`, `load-file` of `language-id.el`(since format-all depends on it), and then load-file of `format-all.el`, and execute above code snippet inside scratch buffer, and then open a simple source code file, edit it to make it un-formatted, and save it, it doesn't format the buffer, and I checked `format-all-mode` variable, it is already `t`, but after I manually execute `format-all-buffer`, it works, besides, after manually execute the command once, the buffer will be auto-formatted once I edit it.

**Comment by lassik** [comment]
Sorry about that! We just added multi-formatter support last week, and that change broke your config.

We now support more than one formatter per language and no longer automatically assign a default formatter to each language. That means `format-all-mode` does nothing by default unless you explicitly set a formatter for a buffer. (That, in turn, means that it ought to be safe to leave `format-all-mode` enabled in all buffers, even those you don't want to be formatted; this is new.)

The quickest fix to your problem is to do `M-x format-all-buffer` interactively in each buffer. That command will select a formatter to use if one hasn't been chosen yet for the current buffer. When using a language for which format-all supports more than one formatter (e.g. JavaScript), Emacs will prompt in the minibuffer which formatter you want (with tab completion). When using a language for which we support only one formatter so far, `M-x format-all-buffer` will simply select that formatter, and it will be used for that buffer from that point on.

If you know Emacs Lisp, the new buffer-local variable `format-all-formatters` can be set in a hook function, or in a per-project `.dir-locals.el` file, to select formatters without having to interactively call `M-x format-all-buffer` each time.

We'll fix the documentation snippet you point out; just have to think of what would be the right recommendation now.

**Comment by lassik** [comment]
We should perhaps add some functions like `(format-all-set-formatter (format-all-default-formatter))` that can be called from hooks. Not sure whether or not that's a good idea, since for languages for which we support more than one formatter, it's somewhat arbitrary which one would make the best default.

**Comment by c02y** [comment]
I still like the way the buffer will be auto-formatted without extra config, I think the best strategy is
- if the language only has one formatter, select it by default
- if the language has multiple formatters, select one by default, let the user choose one if he/she doesn't like the default one.

Now no formatter is set by default, I have to set it manually in my init.el file, or manually call `format-all-buffer` every time I open a new Emacs session or a new language buffer. I don't know why this is designed like this, it need more config, and if I want one buffer to be formatted automatically, I won't add it to the hook.

**Comment by lassik** [comment]
We should figure out what people need; I don't really know what kinds of hooks most people are using.

We could provide a `(format-all-default)` function which would be a low-risk thing that would be easy to add into hook functions without breaking anything else. If that function is run in a buffer whose language format-all doesn't support, it could simply be a no-op; otherwise it would select a default formatter if no formatter is set via the `format-all-formatters` variable. Would that work for you?

**Comment by c02y** [comment]
IMHO the package user would 
1. If I want the buffer to be auto-formatted when I save it, I will set it like adding it to the hook (after-change-major-mode-hook or before-save-hook, I like before-save-hook since it should format the buffer before-save)
2. If I don't want the buffer to be auto-formatted, I won't set it 
3. I can manually execute the command like `format-all-buffer` to manually format the buffer if I didn't set it auto-formatted.

As for the one or more formatters for a language, the strategy can be the one I told earlier.

Users really don't care other things.

And I think code snippet I posted in the first place is still too much, it should be written into the package, and provide only a function or variable for the user to.
- a feature to auto-format the buffer or not
- change the default formatter or not
- a command for the user to manually format the buffer, if the buffer is not supported, do nothing


So let's analyze the code snippet to auto-format:
~~~
(defvar my-auto-format-modes '(c-mode c++-mode cmake-mode emacs-lisp-mode
                                        fish-mode go-mode json-mode lua-mode
                                        markdown-mode python-mode rust-mode
                                        sh-mode toml-mode yaml-mode))
  (defvar my-auto-format-dirs '("" ""))
  (defun my-auto-format-buffer-p ()
    (and (member major-mode my-auto-format-modes)
         (buffer-file-name)
         (save-match-data
           (let ((dir (file-name-directory (buffer-file-name))))
             (cl-some (lambda (regexp) (string-match regexp dir))
                      my-auto-format-dirs)))))
  (defun format-buffer-before-save ()
    (format-all-mode (if (my-auto-format-buffer-p) 1 0)))
  (add-hook 'after-change-major-mode-hook 'format-buffer-before-save)
~~~

Variables like `my-auto-format-modes` and `my-auto-format-dirs` should be provided in package and leave it empty to let the user set.

`my-auto-format-buffer-p` and `format-buffer-before-save` should be written in the package, users won't care about these two functions, once `my-auto-format-modes` and `my-auto-format-dirs` are set, Emacs will auto-format the buffer. Now `after-change-major-mode-hook` and `format-buffer-before-save` won't even be necessary.

A command like `format-all-formatter` will be provided for users to change the default formatter which is already set in the package like:
~~~
(format-all-formatter 'a-major-mode "the-formatter-name")
~~~

**Comment by smartepsh** [comment]
Same problem.

I agree with @c02y that a default formatter should be set for each language and user can change it manually when needed.

I use `use-package` to manage emacs packages. The configuration I want should looks like below:

```emacs-lisp
(use-package format-all
  :hook (elixir-mode . format-all-mode)
  :hook (emacs-lisp-mode . format-all-mode)
  ;; or for all program languages 
  :hook (prog-mode . format-all-mode)
  ;; change default formatter manually
  :init
  (setq formatters '((elixir-mode . "elixir-formatter") (ruby-mode . "ruby-formatter")))
```

It's enough for me. 😃 

And I don't think anyone will format a language in some directory (project) without format the same language in another directory.....So I think it’s enough to judge whether formatting is needed through the language mode.

**Comment by lassik** [comment]
> I don't think anyone will format a language in some directory (project) without format the same language in another directory.....

On the contrary, I'd expect that to be quite common. I edit code from many projects that don't use any formatter.

**Comment by lassik** [comment]
@c02y @smartepsh Just pushed a commit 0ff2ca0 that adds back default formatter support:

> * Variable `format-all-default-formatters`. Can be customized. The default default formatters are the same ones as they were before multi-formatter support was added.
> 
> * Command `format-all-ensure-formatter`. If a formatter hasn't been set for the current language, sets it to the default one for the language.

The default formatter is still not automatically applied; you have to call `(format-all-ensure-formatter)`. But you can call it in a hook.

**Comment by lassik** [comment]
As usual, sorry about the long delay.
