### ISSUE TITLE
Use black for python 

### ISSUE THREAD

**Issue by leiserfg** [lassik/emacs-format-all-the-code#15]
Black has a better output than autopep8 and is faster than yapf.  And they hate making black configurable, just like format-all :smile:

**Comment by lassik** [comment]
I'm in favor of this change. When format-all was started, it wasn't clear how we should configure formatters. We have since talked to the folks from the Unibeautify project and decided that it would be best to leave configurable formatting to Unibeautify since they already have a cross-editor configuration file and a good framework being actively developed (discussed in issue #7 and a bit in #2 ). I have since started work on a separate Unibeautify package for Emacs, as discussed in #7.

With Unibeautify handling the configurable formatting, it would probably be best to have the main "anti-bikeshedding" formatter for each language being supported by format-all. It does indeed seem that Black would be the best choice for Python. I don't have any stats on what formatters people are using so I don't know how much anyone depends on the current choice, `autopep8`. My impression is that Black is basically `autopep8` taken even further, so I suppose it shouldn't cause too much trouble. Python seems to have a very standardization-happy language community anyway.

**Comment by leiserfg** [comment]
Then I will make a pr as soon as I do it

**Comment by lassik** [comment]
Thanks for the initiative :) Please wait until the end of the week. I'm rewriting the core data structure to address #14. Should be done in 2-3 days.

**Comment by lassik** [comment]
Rewrite done, barring a little mechanical work. I'll finish it tonight. Already added `black`.

**Comment by lassik** [comment]
The version using `black` is now in MELPA. I'll leave this issue open for some time in case people want to complain about the fact that is converts single-quoted strings to double-quoted ones :p
