### ISSUE TITLE
Prettier supports HTML, Angular, Vue now

### ISSUE THREAD

**Issue by ztlevi** [lassik/emacs-format-all-the-code#22]
As the title tells, it might be a good idea to switch to prettier for web-mode since it covers more support.😀

**Comment by ztlevi** [comment]
It looks like `tsx` file support is missing. `tsx` is a typescript file using React. 

Right now, prettier formatter using modes to identify which parser to use. But I'm not sure if prettier will pick the right parser for us. If so, it might be easier to implement based on the file extension rather than the modes. Because sometimes, people are using `web-mode` to edit `js, ts, jsx, tsx, html` files. 

Besides, inside the `prettier` formatter definition:
```
   (web-mode
    (and (equal "none" (symbol-value 'web-mode-engine))
         (let ((ct (symbol-value 'web-mode-content-type)))
           (cond ((equal ct "css") "css")
                 ((equal ct "javascript") "babylon")
                 ((equal ct "json") "json")
                 ((equal ct "jsx") "babylon")))))
```
We format the `web-mode` based on the content. It seems unnecessary now.

**Comment by lassik** [comment]
Thanks for looking into this. The relevant `web-mode` variables are (copied from #14):

> * `web-mode-content-type`
> * `web-mode-engine`
> * `web-mode-minor-engine`

This list in the source code makes it clear:

> [List of all engines and content types in web-mode source](https://github.com/fxbois/web-mode/blob/e31d1dd4ee436db8aaca3f35223af5a05fb47dec/web-mode.el#L800) `web-mode-engine` are the ones on the left (e.g. `ctemplate`) while `web-mode-minor-engine` are the ones on the right (e.g. `jinja`).

I think web-mode itself sets those variables based on the file name extension (and probably other clues) so we should be able to rely on web-mode's auto-detection of the language by looking at them.

The content-type is needed to give the right `--parser` flag for prettier (e.g. `prettier --parser babylon` for JavaScript code, and `prettier --parser css` for CSS code. The file name extension is not always available, because we also support formatting temporary buffers (e.g. you can make a buffer `foo` that is not visiting any file, switch to e.g. `js-mode` and then format that buffer using `M-x format-all-buffer`). Therefore a solution that doesn't rely on file name extension would be simpler.

**Comment by ztlevi** [comment]
Oh, right. Forget the buffer formatting support. Did you use the `stdin` to support buffer formatting?

Emm, I just want to point out that many people are using web-mode to edit `tsx` files. And the value `web-mode-content-type` under these `tsx` files is `jsx`.

**Comment by lassik** [comment]
Web-mode has an issue about TypeScript support (https://github.com/fxbois/web-mode/issues/585) and it sounds like they implemented it already in 2015, but I can't find any mention of `typescript` or `tsx` in the latest `web-mode.el`.

**Comment by lassik** [comment]
It's in the regexps:

```
(defvar web-mode-content-types
...
    ("javascript" . "\\.\\([jt]s\\|[jt]s\\.erb\\)\\'")
...
    ("jsx"        . "\\.[jt]sx\\'")
```

So they recognize both TypeScript and TSX, but use JavaScript and JSX modes because the languages are so similar. And yet prettier has different parsers for JavaScript/JSX (`babylon`)  and TypeScript/TSX (`typescript`). Probably there are some minor differences between those parsers since they still have both of them in the latest version, so we should pick exactly the right one, even if the other one is "close enough" for some files.

From that basis, I think your idea to look at the filename extension is the best we can do currently. We can do that via `(and (buffer-file-name) (string-match "\\.tsx?\\'" (buffer-file-name)))`.

**Comment by lassik** [comment]
Sorry, I didn't fully understand your original request until now 😄 Haven't used web-mode's TypeScript support so I thought it just worked like all the other languages...

**Comment by lassik** [comment]
I did some light testing and everything *should* work now :) The HTML/Angular/Vue changes and the TypeScript fix went into the same commit, I neglected to mention TypeScript in the commit message.

**Comment by lassik** [comment]
web-mode supports tons of HTML templating engines, but it seems prettier doesn't support any of them yet except for Angular and Vue.

**Comment by lassik** [comment]
Oh yeah, almost forgot. I left HTML Tidy support for HTML in the code as well, so now there are two formatters that support plain HTML without templating. I was thinking of making a variable `format-all-formatters` for specifying formatters and their command line arguments, as discussed a long time ago in #6. There seems to be demand for that, and we are taking our time to progress with Unibeautify, so people could write hooks to use their favorite formatters and options in the meantime.

**Comment by lassik** [comment]
It would be a simple change at this point. The framework already supports defining multiple formatters.

**Comment by ztlevi** [comment]
Great, great! I didn't realize the github emails is hidden in my email's notification section. Sorry for it takes so long to response.

So what would be the current behavior of the web-mode formattting? Does it look up in the `format-all-mode-table` for the first formatter?

**Comment by ztlevi** [comment]
> but I can't find any mention of typescript or tsx in the latest web-mode.el.

As for the `jsx` support in `web-mode`, it's kind of "fully supported" but not optimized for it. There are several  setups you might want to consider:
1. Emacs Tide's [documentation](https://github.com/ananthakumaran/tide#jsx) uses `web-mode` in `jsx` and `tsx` for demonstration. 
2. Spacemacs uses `rjsx-mode` for `jsx` and [typescript-tsx-mdoe](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+lang/typescript/packages.el#L99) for `tsx` which is inherited from `web-mode`. In this case, I'm not sure formatting strategies will be inherited or not. Maybe it needs to be implemented in `format-all` and I believe it's not a hard one.
3. Doom emacs uses `rjsx-mode` for `jsx` and `web-mode` for `tsx`.

**Comment by lassik** [comment]
@ztlevi Did we resolve everything in this issue (except the multi-formatter support)?

**Comment by ztlevi** [comment]
@lassik Oh, I'm sorry. I didn't catch up my personal email recently, kind of busy switching to a new job. How's the progress on multi-formatter?
