### ISSUE TITLE
Make it possible to ignore unknown formatter error

### ISSUE THREAD

**Issue by benjaminor** [lassik/emacs-format-all-the-code#48]
Hi,

I enjoy using format-all and I have actually enabled it in like this in all prog-modes as I was too lazy to enable it in each mode separately:
``` lisp
(use-package format-all
  :config
  (add-hook 'prog-mode-hook (lambda () (format-all-mode t))))
```
However, now I have the problem that in some modes without an apt formatter, I get the error *"Don't know how to format ... code"*.

I would suggest that users can set a variable which, if true, makes format-all ignore this error and save the buffer anyway.

What do you think of this idea?
In case you agree I have created a pull request which would solve this issue.

**Comment by lassik** [comment]
Thank you for the bug report and sorry for the long delay in responding. I don't have a lot of time to put into Emacs these days (unfortunately this is a common problem with editor extensions - most programmers spend their thinking time on other things, which is a big reason e.g. MELPA review are slow). Lately all my Emacs time has gone into preparing Sunrise Commander for a MELPA release so my responses have been extra slow.

Anyway, to the best of my understanding this issue should now be fixed in the latest commit e37fce5. Please let me know if it doesn't solve your problem.
