### ISSUE TITLE
Configure SQL dialects or keywords for sqlparser

### ISSUE THREAD

**Issue by amosbird** [lassik/emacs-format-all-the-code#54]
Is there a way to configure sqlparser via format-all? https://github.com/andialbrecht/sqlparse

**Comment by lassik** [comment]
Sorry, missed this one. Unfortunately there is not, since sqlformat does not use a configuration file and wants its options as command line arguments instead. The Custom Args Procrastination Thread (#27) is still going... I'm also looking for new maintainers but no-one has expressed interest so far.

By the way, make sure you have the latest version 0.3.0 of sqlparse. There's a bugfix that makes semicolons work together with the alignment option (which format-all uses).

**Comment by lassik** [comment]
Hey, this now works in the `multi-formatter` branch. Please follow issue #27 if interested. I'll merge this stuff into the `master` branch, which goes into MELPA, once we're happy that it's stable enough and not too confusing.
