### ISSUE TITLE
Symbol’s function definition is void: mapcan

### ISSUE THREAD

**Issue by JohnEmhoff** [lassik/emacs-format-all-the-code#66]
I get the error `Symbol’s function definition is void: mapcan` when I try to run `M-x format-all-mode`. I'm somewhat at a loss for how to debug, but I'm happy to look into it if you can point me in the right direction.

I have emacs 25.2.2, format-all 20191208.1946, and cl-lib 0.6.1

**Comment by JohnEmhoff** [comment]
Looks like adding a `(require 'cl)` to the format-all source fixes this problem for me.

**Comment by lassik** [comment]
Oops, my mistake. `mapcan` is a built-in function in the latest Emacs (26.x) but apparently it was made built-in only recently. As you noticed, it used to only be in the `cl` package. Since `format-all` is supposed to be compatible all the way back to Emacs 24, I'll revert to using the CL version, `cl-mapcan`.

If you edit `format-all.el` to change `mapcan` to `cl-mapcan` and remove the `(require 'cl)` line, does it work for you in `emacs -Q` (i.e. a fresh Emacs launched with default settings)? If it does, I'll commit that change so you can use the standard version of format-all.

**Comment by JohnEmhoff** [comment]
Yep, removing the require and changing mapcan to cl-mapcan works. Thanks!

**Comment by lassik** [comment]
Thanks! This commit should fix it. Let me know if it doesn't.
